import { Router } from "express";
import camionetasRouter from "./camionetas.routes.js";
import tractoresRouter from "./tractores.routes.js";
import colectivosRouter from "./colectivos.routes.js";
import reparacionesRouter from "./reparaciones.routes.js";
import checklistRouter from "./checklist.routes.js";
import programaChecklistRouter from "./programachecklist.routes.js";
import kilometrosRouter from "./kilometros.routes.js";
import servicesRouter from "./services.routes.js";
import paradasRouter from "./paradas.routes.js";
import trabajosCamionetaRouter from "./trabajoscamioneta.routes.js";
import trabajosTractorRouter from "./trabajostractor.routes.js";
import cronRouter from "./cron.routes.js";
import configRouter from "./config.routes.js";
import visitasRouter from "./visitas.routes.js";
import servicesTractorRouter from "./servicestractor.routes.js";
import horometrosTractorRouter from "./horometrostractor.routes.js";
import servicesColectivoRouter from "./servicescolectivo.routes.js";
import kilometrosColectivoRouter from "./kilometroscolectivo.routes.js";
import historialTractorRouter from "./historialtractor.routes.js";
import centrosCostoRouter from "./centroscosto.routes.js";
import personalRouter from "./personal.routes.js";
import tareasRouter from "./tareas.routes.js";
import partesRouter from "./partes.routes.js";
import periodosRouter from "./periodos.routes.js";

const router = Router();

router.get("/", (req, res) => res.json({ message: "API funcionando" }));
router.use("/camionetas", camionetasRouter);
router.use("/tractores", tractoresRouter);
router.use("/colectivos", colectivosRouter);
router.use("/reparaciones", reparacionesRouter);
router.use("/checklist", checklistRouter);
router.use("/programa-checklist", programaChecklistRouter);
router.use("/kilometros", kilometrosRouter);
router.use("/services", servicesRouter);
router.use("/services-tractor", servicesTractorRouter);
router.use("/horometros-tractor", horometrosTractorRouter);
router.use("/services-colectivo", servicesColectivoRouter);
router.use("/kilometros-colectivo", kilometrosColectivoRouter);
router.use("/historial-tractor", historialTractorRouter);
router.use("/paradas", paradasRouter);
router.use("/trabajos-camioneta", trabajosCamionetaRouter);
router.use("/trabajos-tractor", trabajosTractorRouter);
router.use("/cron", cronRouter);
router.use("/config", configRouter);
router.use("/visitas", visitasRouter);
router.use("/centros-costo", centrosCostoRouter);
router.use("/personal", personalRouter);
router.use("/tareas", tareasRouter);
router.use("/partes", partesRouter);
router.use("/periodos", periodosRouter);

export default router;
